// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJXGYDkgX1v1bSMTiFNuWTVOunJkXg9Q',
    appId: '1:130537228101:web:fcb29ef5821b329b8e202c',
    messagingSenderId: '130537228101',
    projectId: 'core-crm-e7484',
    authDomain: 'core-crm-e7484.firebaseapp.com',
    storageBucket: 'core-crm-e7484.firebasestorage.app',
    measurementId: 'G-PG88TEW9W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1AMRnxkiMLlqu29zfWV0PiO3zCFhDJY',
    appId: '1:130537228101:android:686643fed210eefa8e202c',
    messagingSenderId: '130537228101',
    projectId: 'core-crm-e7484',
    storageBucket: 'core-crm-e7484.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_rum3t-BQKY5tBfIM5EgH-XEuueU8CY',
    appId: '1:130537228101:ios:1823ca0938ff2fae8e202c',
    messagingSenderId: '130537228101',
    projectId: 'core-crm-e7484',
    storageBucket: 'core-crm-e7484.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtyflowCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU_rum3t-BQKY5tBfIM5EgH-XEuueU8CY',
    appId: '1:130537228101:ios:1823ca0938ff2fae8e202c',
    messagingSenderId: '130537228101',
    projectId: 'core-crm-e7484',
    storageBucket: 'core-crm-e7484.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtyflowCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJXGYDkgX1v1bSMTiFNuWTVOunJkXg9Q',
    appId: '1:130537228101:web:24e55d96f15d5f8c8e202c',
    messagingSenderId: '130537228101',
    projectId: 'core-crm-e7484',
    authDomain: 'core-crm-e7484.firebaseapp.com',
    storageBucket: 'core-crm-e7484.firebasestorage.app',
    measurementId: 'G-W8D7VHETHN',
  );

}