// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHV3lmkZBV4arXDY46FJkiL62u3fgZlN8',
    appId: '1:187898452816:web:271b889dbf27e439b5aa55',
    messagingSenderId: '187898452816',
    projectId: 'joinz-app',
    authDomain: 'joinz-app.firebaseapp.com',
    storageBucket: 'joinz-app.firebasestorage.app',
    measurementId: 'G-XZB1K1TEZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj4vG7vhNwkrWiLrlmdIv3PMAdbD_jReo',
    appId: '1:187898452816:android:e525401383109935b5aa55',
    messagingSenderId: '187898452816',
    projectId: 'joinz-app',
    storageBucket: 'joinz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcBJblNuMo99u1L6R0TTqCJER3gwQ3Oi4',
    appId: '1:187898452816:ios:065287eeb66016e2b5aa55',
    messagingSenderId: '187898452816',
    projectId: 'joinz-app',
    storageBucket: 'joinz-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtyflowCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcBJblNuMo99u1L6R0TTqCJER3gwQ3Oi4',
    appId: '1:187898452816:ios:065287eeb66016e2b5aa55',
    messagingSenderId: '187898452816',
    projectId: 'joinz-app',
    storageBucket: 'joinz-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterRealtyflowCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHV3lmkZBV4arXDY46FJkiL62u3fgZlN8',
    appId: '1:187898452816:web:2e696c339e44f37eb5aa55',
    messagingSenderId: '187898452816',
    projectId: 'joinz-app',
    authDomain: 'joinz-app.firebaseapp.com',
    storageBucket: 'joinz-app.firebasestorage.app',
    measurementId: 'G-K6JK9WJ5RL',
  );
}
